### ISSUE TITLE
Syntax error, unrecognized expression on checkboxes

### ISSUE THREAD

**Issue by kashifnaseer** [jiripospisil/parsley-rails#19]
I'm facing the same issue which is mentioned at https://github.com/guillaumepotier/Parsley.js/issues/881. This issue has already been fixed in Parsley.js itself. 

How i can get this working in parsley-rails-2.0.7.0 ?

**Comment by sgrosse** [comment]
Try using the branch from bayu41 with `v2.2.0-rc1` until it gets merged.

`gem 'parsley-rails', git: "git@github.com:bayu41/parsley-rails.git", branch: "v2.2.0-rc1"`
