### ISSUE TITLE
Best practices for Turbolinks?

### ISSUE THREAD

**Issue by rossinkiwi** [jiripospisil/parsley-rails#24]
Do you have suggestions for how to best incorporate Parsley.js with Turbolinks enabled pages?
I started out with:

    function initParsley() {
      $("form.has_validations").length && $("form.has_validations").parsley()
    };
    
    var run_ready;
    function run_ready() {
      initParsley();
    };
    
    $(document).ready(run_ready);
    $(document).on('turbolinks:load', run_ready);

But found that on turbolinks restore events, I would see duplicate parsley error annotations:
![image](https://cloud.githubusercontent.com/assets/8278320/22706654/4ecf8bf8-ed2d-11e6-9cf1-4c22b815a942.png)

The only way found around this seemed a bit hacky:

    function initParsley() {
      $("form.has_validations").find("ul.parsley-errors-list li").remove();  
      $("form.has_validations").length && $("form.has_validations").parsley().reset();
      $("form.has_validations").length && $("form.has_validations").parsley().validate();
    };
    
    var run_ready;
    function run_ready() {
      initParsley();
    };
    
    $(document).ready(run_ready);
    $(document).on('turbolinks:load', run_ready);

Do you have any suggestions for best practices when using parsley-rails with Turbolinks 5 enabled?

**Comment by jiripospisil** [comment]
Hello, I'm sorry for the late response. I think you can make it more compact as follows (no need to the overall ready callback):

```
$(document).on("turbolinks:load", function() {
    var form = $('form.has_validations').parsley();

    $(document).one('turbolinks:before-cache', function() {
        if (form) {
            form.destroy();
        }
    })
});
```

**Comment by rossinkiwi** [comment]
Thank you - very helpful!  I did have to modify your approach slightly to avoid 2 issues:

1) Calling .parsley() on empty jQuery object throws a warning "You must bind Parsley on an existing element.".  To avoid this, I needed to test length before calling parsley.

2) form.destroy() does not set form variable to null, so form.destroy gets called again a 2nd time when navigating away from the subsequent page.

Here's what the modified code looks like;

```javascript 
$(document).on("turbolinks:load", function() {
    var form = $('form.has_validations');
    if ( form.length ) {
      var parsley_form = form.parsley();
    }
    $(document).on('turbolinks:before-cache', function() {
        if (parsley_form) {
            parsley_form.destroy();
            parsley_form = null;
        }
    })
});

**Comment by obie** [comment]
This appears to work well for me using Turbolinks 5.2

```js
require('parsleyjs');
ParsleyConfig.autoBind = false;

$(document).on('turbolinks:load', function() {
  $('[data-parsley-validate]').each(function() {
    new Parsley.Factory(this)
  });
});
```

**Comment by 0agautam** [comment]
> This appears to work well for me using Turbolinks 5.2
> 
> ```js
> require('parsleyjs');
> ParsleyConfig.autoBind = false;
> 
> $(document).on('turbolinks:load', function() {
>   $('[data-parsley-validate]').each(function() {
>     new Parsley.Factory(this)
>   });
> });
> ```

thanks this saved my day
