### ISSUE TITLE
//= require parsley.remote

### ISSUE THREAD

**Issue by Sohair63** [jiripospisil/parsley-rails#27]
This file is not the part of your gem ?
https://github.com/guillaumepotier/Parsley.js/blob/9b9b44fcb530565d7d489fca0e1343b3c162fdfd/src/parsley/remote.js

**Comment by jiripospisil** [comment]
Hello, that's just an error in this repository's README file. The remote validation functionality is now part of the main distribution. I will fix it. Thank you for pointing that out.
