### ISSUE TITLE
Update to latest version of Parsley

### ISSUE THREAD

**Issue by mkbctrl** [jiripospisil/parsley-rails#29]
Hey there, 

are you planning any updates in close future?

**Comment by jiripospisil** [comment]
Hello, I've created a PR for the update #30. Would you mind testing things out before I push it to rubygems? Thanks.

```
gem 'parsley-rails', github: 'jiripospisil/parsley-rails', branch: 'release_281'
```

**Comment by mkbctrl** [comment]
Sure, I can do this right now

**Comment by mkbctrl** [comment]
@jiripospisil worked fine for me out of the box. Sure it's unstyled, but works just like the current version. Would need any more details from me?

<img width="604" alt="screen shot 2018-09-28 at 13 13 14" src="https://user-images.githubusercontent.com/10107362/46205268-493e7580-c320-11e8-9199-858e32fddf31.png">

**Comment by mkbctrl** [comment]
I will be creating more complex setup today, I should have more complex setup in coming days

**Comment by jiripospisil** [comment]
Alright, I've just published the new version. Thank you for testing.
